import mongoose from "mongoose";
const UserSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    collegename:{
        type:String,
        required:true,
    },
    branch:{
        type:String,
        required:true,
    },
    mobile:{
        type:String,
        required:true,
    },
    address:{
        type:String,
        required:true,
    },
    city:{
        type:String,
        required:true,
    },
    state:{
        type:String,
    },
    gender:{
        type:String,
    },
    year:{
        type:Number,
        required:true,  
    },
    dob:{
        required:true,
        type:Date,
    },
    district:{
        reuqired:true,
        type:String,
    },
    profileimage:{
        type:String,
    },
    communities:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Community",
        },
    ],
    sendRequests:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'USER',
        }
    ],
    receivedRequests:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'USER',
        }
    ],
    connections:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'USER',
        }
    ],
    onboarded:{
        type:Boolean,
        default:false,
    }
})
const userModel=mongoose.models.USER||mongoose.model("USER",UserSchema);
export default userModel;